name: Uppdatera RSS-flöde

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Sätt upp PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Visa PHP-version
      run: php -v

    - name: Hämta flöden
      run: php -d log_errors=1 -d error_log=php://stderr fetch.php

    - name: Commit och pusha ändringar
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "Uppdatera RSS-flöden"
          git push
        else
          echo "Inga ändringar att committa"
        fi
